server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedHeaders: "*"
                allowedMethods:
                  - POST

          routes:
            - id: users
              uri: lb://users-service
              predicates:
                - Path=/users/**
                - Method=POST
              filters:
                - StripPrefix=1

            - id: catalogue
              uri: lb://catalogue-service
              predicates:
                - Path=/catalogue/**
                - Method=POST
              filters:
                - StripPrefix=1

            - id: orders
              uri: lb://orders-service
              predicates:
                - Path=/orders/**
                - Method=POST
              filters:
                - StripPrefix=1

            - id: comms
              uri: lb://comms-service
              predicates:
                - Path=/comms/**
                - Method=POST
              filters:
                - StripPrefix=1

app:
  gateway:
    public-paths: /users/api/v1/auth/token,/users/api/v1/users,/catalogue/api/v1/books,/actuator

management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: health, info, gateway
